# Generated by Django 4.2.1 on 2023-05-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='units_of_measurement',
            field=models.CharField(default='kg', max_length=50, verbose_name='кг'),
        ),
    ]
