# Generated by Django 4.2.1 on 2023-05-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_recipe_image_shoppingcard_isfaworite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='units_of_measurement',
            new_name='measurement_unit',
        ),
    ]
