# Generated by Django 4.2.1 on 2023-05-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_token',
        ),
    ]
